browser: chrome
base_url: "https://www.facebook.com/"

credentials:
  username: "your_email@test.com"
  password: "your_password"

paths:
  driver_path: "C:/drivers/chromedriver.exe"
  screenshots: "reports/screenshots/"
  logs: "reports/logs/"
